version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-soft}
      PGDATA: /var/lib/postgresql/data
    volumes:
      # Локальное хранилище (не коммитим в Git!)
      - ./postgres/data:/var/lib/postgresql/data
      # Автоматическое восстановление при первом запуске
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
    postgres:
      driver: bridge

