spring.application.name=SoftManage

server.port=9999

# URL ? ????, ??? ????, ???? ? ????
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=default
spring.datasource.password=default
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

